server.port: 8003

spring.datasource:
  url: jdbc:mysql://10.10.10.63:3306/finance?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 62S5RkCkblW9E9YlJ4
  driver-class-name: com.mysql.jdbc.Driver
  hikari:
    connection-timeout: 30000
    connection-test-query: SELECT 1
    max-lifetime: 1800000
    minimum-idle: 5
    idle-timeout: 180000
    maximum-pool-size: 10
    pool-name: HikariCP-pool1
  type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
